//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddUP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Ads = new HashSet<Ads>();
        }
    
        public int user_id { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
    
        public virtual ICollection<Ads> Ads { get; set; }
    }
}
